# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b76a7ac31147ac82d0220b6d948110119d7ed3f73525e4b38f16560df462c234a498e60f2b108dac7d21698107673f228ed552d185bc4d5829bc69cd6ead466

test:
  secret_key_base: 7a2f5579d4289f79fb2a8b7f1c3f3ad17221ff5d7ff5fca22d7ef8e54295635d47a558a77a63777a5d9a3406d3b8883311af50dea2cdfac6ee0bd5f3e4804e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
